These are the [merl-an] logs, i.e. things that went wrong / were worth logging
on the [merl-an] side of things.
  $ cat irmin_data/logs.json
  ["Error","Failure(\"exception while running [ocamlmerlin server complete-prefix -prefix 'n'' -position '308:28' -filename irmin/src/irmin/watch.ml < irmin/src/irmin/watch.ml]: Yojson.Json_error(\\\"Blank input data\\\")\\n\")"]
  ["Log","File \"irmin/src/irmin/version.ml\": there are no samples for query [complete-prefix]."]
  ["Log","File \"irmin/src/irmin/version.ml\": there are no samples for query [locate]."]
  ["Log","File \"irmin/src/irmin/version.ml\": there are no samples for query [occurrences]."]
  ["Warning","File \"irmin/src/irmin/unix/info.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/unix/info.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/unix/info.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/unix/info.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/type.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/type.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/type.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/type.mli\" couldn't be parsed and was ignored.\n"]
  ["Error","Failure(\"exception while running [ocamlmerlin server complete-prefix -prefix 'h'' -position '333:21' -filename irmin/src/irmin/store.ml < irmin/src/irmin/store.ml]: Yojson.Json_error(\\\"Blank input data\\\")\\n\")"]
  ["Warning","File \"irmin/src/irmin/storage.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/storage.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/storage.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/storage.mli\" couldn't be parsed and was ignored.\n"]
  ["Error","Failure(\"exception while running [ocamlmerlin server complete-prefix -prefix 'h'' -position '316:9' -filename irmin/src/irmin/proof.ml < irmin/src/irmin/proof.ml]: Yojson.Json_error(\\\"Blank input data\\\")\\n\")"]
  ["Warning","File \"irmin/src/irmin/merge.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/merge.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/merge.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/merge.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/mem/irmin_mem.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/mem/irmin_mem.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/mem/irmin_mem.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/mem/irmin_mem.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lru.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lru.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lru.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lru.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lock.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lock.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lock.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/lock.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/irmin.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/irmin.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/irmin.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/irmin.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/dot.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/dot.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/dot.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/dot.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/data/fixed_size_string_set.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/data/fixed_size_string_set.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/data/fixed_size_string_set.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/data/fixed_size_string_set.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/conf.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/conf.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/conf.mli\" couldn't be parsed and was ignored.\n"]
  ["Warning","File \"irmin/src/irmin/conf.mli\" couldn't be parsed and was ignored.\n"]

  $ cat irmin_pack_data/logs.json

  $ cat irmin_pack_test_data/logs.json
