#!/bin/sh
D=`mktemp -d`
cleanup()
{
  rm -rf "$D"
}

trap cleanup EXIT
OUT="$D/jenga.output"
mkfifo "$OUT"
exec "$@" | tee "$OUT" &
PID=$!

grep --line-buffered "^\*\*\* jenga: polling for filesystem changes$" "$OUT" |
while read line; do
  echo "*** merlin: reloading cache"
  killall --user "$USER" --signal SIGUSR1 --regexp '^ocamlmerlin.*'
done
wait "$PID"
