#!/bin/sh

src_dir="$(dirname ${BASH_SOURCE[0]})/.."
cd "$src_dir"
src_dir=$(realpath -e $(pwd))
cd - > /dev/null
$(dirname ${BASH_SOURCE[0]})/%%OCAMLMERLIN_PATH%% $@ \
    | jq 'del(.timing)' \
    | sed -e "s:$src_dir/::" \
    | sed -e 's:"/.*/\.opam/[^/]*/\([^"]*\)":"~opam/\1":' \
    | sed -e 's:\\n:\
:g'
