
  $ cat >foo.ml <<EOF
  > type 'k t = 'k baz
  > and 'k baz =
  >   | Foo
  >   | Bar of 'k t
  > EOF

  $ $MERLIN single type-enclosing -position 4:15 -verbosity 1 \
  > -filename ./foo.ml < ./foo.ml
  {
    "class": "exception",
    "value": "Stack overflow
  Raised by primitive operation at Ctype.expand_abbrev in file \"src/ocaml/typing/ctype.ml\" (inlined), line 1655, characters 2-57
  Called from Ctype.try_expand_once in file \"src/ocaml/typing/ctype.ml\", line 1675, characters 22-44
  Called from Ctype.try_expand_safe in file \"src/ocaml/typing/ctype.ml\", line 1681, characters 6-28
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1687, characters 12-27
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  Called from Ctype.try_expand_head in file \"src/ocaml/typing/ctype.ml\", line 1688, characters 6-38
  ",
    "notifications": []
  }
