val raise_error : exn -> unit
val catch_errors : (unit -> 'a) -> exn list * (exn, 'a) Misc.sum

(* Keep track of type variables generated by error recovery *)
val erroneous_type_register : Types.type_expr -> unit
val erroneous_type_check : Types.type_expr -> bool
