open Std

exception Weak_error of exn

val raise_error: exn -> unit
val catch_errors: (unit -> 'a) -> exn list * 'a or_exn

(* Keep track of type variables generated by error recovery *)
val erroneous_type_register: Types.type_expr -> unit
val erroneous_type_check: Types.type_expr -> bool
val erroneous_expr_check: Typedtree.expression -> bool

val relax_typer: bool fluid

include module type of Merlin_types_custom
